import Head from "next/head";

function HomePage() {
  return (
    <div>
      <Head>
        <title>Next.js Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Home - index.js</h1>
      </main>
    </div>
  );
}

export default HomePage;
